version: '2'

services:

### PHP Composer Container ####################################
  composer-install:
    build: ./php/composer
    volumes_from:
      - volume_application
    command: [php, artisan, 'chrono:init']

### PHP Database Container ####################################
  database-install:
    build: ./php/database
    volumes_from:
      - volume_application
    links:
      - mariadb:db
    environment:
      APP_TIMEZONE: "$APP_TIMEZONE"
      APP_KEY: "$APP_KEY"
      APP_ENV: "$APP_ENV"
      APP_DEBUG: "$APP_DEBUG"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      ADMIN_EMAIL: "$ADMIN_EMAIL"
      ADMIN_PASSWORD: "$ADMIN_PASSWORD"
      ADMIN_NICKNAME: "$ADMIN_NICKNAME"
      ADMIN_GENDER: "$ADMIN_GENDER"
      ADMIN_ADDRESS: "$ADMIN_ADDRESS"

### PHP CLI Container ####################################
  php-cli:
    build: ./php/cli
    volumes_from:
      - volume_application
    links:
      - mariadb:db
    environment:
      APP_TIMEZONE: "$APP_TIMEZONE"
      APP_KEY: "$APP_KEY"
      APP_ENV: "$APP_ENV"
      APP_DEBUG: "$APP_DEBUG"

### PHP Cron Container ####################################
  php-cron:
    build: ./php/cron
    volumes_from:
      - volume_application
    links:
      - mariadb:db
      - redis
    environment:
      APP_TIMEZONE: "$APP_TIMEZONE"
      APP_KEY: "$APP_KEY"
      APP_ENV: "$APP_ENV"
      APP_DEBUG: "$APP_DEBUG"
    restart: always

### PHP Apache Container ####################################
  php-apache:
    build: ./php/apache
    ports:
      - "$WEB_PORT:80"
    volumes_from:
      - volume_application
    links:
      - mariadb:db
      - redis
    environment:
      APP_TIMEZONE: "$APP_TIMEZONE"
      APP_KEY: "$APP_KEY"
      APP_ENV: "$APP_ENV"
      APP_DEBUG: "$APP_DEBUG"
    restart: always

### Node.js Container ####################################
  node:
    build: ./node
    ports:
      - "$NODE_PORT:80"
    links:
      - redis
    restart: always

### Redis Container ####################################
  redis:
    image: redis:3.0
    restart: always

### MariaDB Container ####################################
  mariadb:
    image: mariadb:10.1
    ports:
      - 3306:3306
    volumes_from:
      - volume_data
    environment:
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
    restart: always

### Application Volume Container ####################################
  volume_application:
    build: ./volumes/application
    volumes:
      - ./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/conf.d/extra.ini:/usr/local/etc/php/conf.d/extra.ini
      - ./application:/var/www

### Data Volume Container ####################################
  volume_data:
    build: ./volumes/data
    volumes:
      - ./data/db:/var/lib/mysql
